# Generated by Django 3.2.25 on 2024-10-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yvdfdg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcbxn', models.BigIntegerField()),
                ('reuix', models.BigIntegerField()),
            ],
        ),
    ]
